### PR TITLE
Ansible multios

### PR DESCRIPTION
**Pull request by grem11n**
## Changelist
* Split the Ansible role into multiple files
* Add `ansible_os_family` for EPEL installation
* Add tests for Ansible
* Updated the Vault version to the latest stable in the example

## Purpose
* `ansible_os_family` check enables users to create Vault AMIs with different OS e.g. Ubuntu.
* Splitting the configuration files is simply a cosmetic change, but it increases the readability of YAML code.
* Currently, automated tests are only for Ansible code itself. I haven't added any tests for Packer of Terraform because it requires an AWS account and not all the objects are eligible for free-tier.
Also, tests are running only for Ubuntu, because GitHub actions [do not support other Linux distributions](https://help.github.com/en/articles/virtual-environments-for-github-actions#supported-virtual-environments-and-hardware-resources). Anyways, it's better than nothing :)

**P.S.** GitHub Actions is a very good solution for OpenSource projects because it doesn't require any external accounts

### CODE REVIEW

**Comment by lingrino** [comment]
Hey @grem11n thanks for the contribution! I really like the idea of packer supporting multiple OS families. The tests are also very welcome 🎉I'm not sure we have enough code to make it worth splitting up the task, but let's wait for other reviewers.

I've got another PR open (https://github.com/avantoss/vault-infra/pull/14) to update terraform and make some small packer changes. And update the version just like your PR here. I know reviews are a bit delayed at the moment but we'll make sure to get this all resolved.

I'll also look into enabling GitHub Actions, I agree it's great for a project like this.

cc @knehring

**Comment by grem11n** [comment]
@lingrino , thank you!
I don't have any strong opinions on keeping the role in a single file.
Regarding the Vault version, I can revert these changes. It's out of scope of the main purpose of this PR anyways. Just a small side improvement :)

**Comment by lingrino** [comment]
Hey @grem11n sorry to keep this PR around without any updates. I merged another PR shortly after this one that added some multi-os support. If you'd like to support another OS I think it's best to follow [that convention](https://github.com/avantoss/vault-infra/blob/master/packer/ansible/roles/vault/tasks/main.yml#L17-L21) and add conditional blocks using `when: ansible_distribution is "Ubutnu"` (for example). Thank You

**Comment by grem11n** [comment]
Ok, will look into it.
Thank you for letting me know!

**Pull request closed without merging**
