### PR TITLE
Fix instance profile name

### PR DESCRIPTION
**Pull request by zacanger**
Thanks for all your hard work on this! It made getting Vault set up a breeze. I ran into two bugs, this one and #11. Submitted them as separate PRs in case there's an issue with either.

### CODE REVIEW

**Comment by lingrino** [comment]
This one is interesting, I wonder if something changed recently because in my experience `id` and `name` have given the same result. In any case I think it's fine to have `name` here and definitely appreciate the contribution!

**Comment by lingrino** [comment]
Let's wait for @knehring before we merge

**Comment by lingrino** [comment]
cc @knehring

**Comment by knehring** [comment]
According to the terraform docs it looks like it expects the ARN or Name so this should be good. Thanks for the contribution!

**Pull request merged**
